name: Greetings

on: [pull_request, issues]

jobs:freedom
  greeting: Welcome-Friends
    runs-on: ubuntu-latest
    permissions:
      issues: I am yet to know
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'please help me know the issue'
        pr-message: 'please help me k ow the pull'
